# Generated by Django 5.1.1 on 2025-04-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
